[vcs]
type = "git"

[module.semver]
version = "0.0.1"
bump_commit_message_template = "bump: {prev_version_str} -> {version_str}"
version_tag_name_template = "v{version_str}"

[[module.semver.bump_rules]]
branch = "^main$"
when_breaking = "minor"
when_feat = "minor"
when_fix = "patch"

[[module.semver.version_files]]
path = "bumpify/__init__.py"
encoding = "utf-8"

[[module.semver.version_files]]
path = "pyproject.toml"
prefix = "version"
section = "[tool.poetry]"
encoding = "utf-8"

[[module.semver.changelog_files]]
path = "CHANGELOG.md"
encoding = "utf-8"
